[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/images/productdetails/*"
  to = "https://exzbshteqangjyjflhlz.supabase.co/storage/v1/object/public/productdetails/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/websitedata/*"
  to = "https://exzbshteqangjyjflhlz.supabase.co/storage/v1/object/public/websitedata/:splat"
  status = 200
  force = true

[[headers]]
  for = "/images/productdetails/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/websitedata/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"